<?php
require_once __DIR__ . '/../../_app.php';
require_once __DIR__ . '/../../_layout.php';
$id=(int)($_GET['id']??0);$db=connectToDatabase();
$stmt=$db->prepare("SELECT id,customer_number,name,email,user_status,restriction_reason,restricted_by,restricted_at,kyc_level,date_registered,last_login_at,last_login_ip,login_count FROM users WHERE id=? LIMIT 1");$stmt->bind_param('i',$id);$stmt->execute();$user=$stmt->get_result()->fetch_assoc()?:null;$stmt->close();
if(!$user){$db->close();cpv2Go('/control-panel/customers/');}
$email=$user['email'];
$stmt=$db->prepare("SELECT id,account_number,account_type,account_alias,currency,account_status,opened_at,creation_time FROM accounts WHERE user_email=? ORDER BY id DESC");$stmt->bind_param('s',$email);$stmt->execute();$accounts=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();
$stmt=$db->prepare("SELECT id,status,first_name,last_name,occupation,country_of_residence,time_uploaded FROM kyc_data WHERE email=? ORDER BY id DESC LIMIT 1");$stmt->bind_param('s',$email);$stmt->execute();$kyc=$stmt->get_result()->fetch_assoc()?:null;$stmt->close();
$stmt=$db->prepare("SELECT transaction_id,type,amount,currency,status,time FROM transactions WHERE user_email=? ORDER BY time DESC LIMIT 8");$stmt->bind_param('s',$email);$stmt->execute();$tx=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();$db->close();
cpv2Start('Customer Detail','customers');
?>
<section class="op-heading"><div><span class="op-kicker">CUSTOMER RELATIONSHIP</span><h1><?php echo htmlspecialchars($user['name']); ?></h1><p><?php echo htmlspecialchars($user['email']); ?> · <?php echo htmlspecialchars($user['customer_number']?:'No customer number'); ?></p></div><a class="op-btn secondary" href="/control-panel/customers/">Back to customers</a></section>
<section class="op-panel" style="margin-bottom:18px"><div class="op-detail">
<div><dt>Relationship status</dt><dd><?php echo htmlspecialchars($user['user_status']); ?></dd></div><div><dt>KYC level</dt><dd><?php echo (int)$user['kyc_level']; ?></dd></div><div><dt>Registered</dt><dd><?php echo htmlspecialchars(date('M d, Y H:i',(int)$user['date_registered'])); ?></dd></div><div><dt>Last login</dt><dd><?php echo $user['last_login_at']?htmlspecialchars($user['last_login_at']):'—'; ?></dd></div><div><dt>Last login IP</dt><dd><?php echo htmlspecialchars($user['last_login_ip']?:'—'); ?></dd></div><div><dt>Login count</dt><dd><?php echo (int)$user['login_count']; ?></dd></div>
</div>
<?php if(strtolower((string)$user['user_status'])!=='restricted'): ?>
<form method="post" class="op-form" style="margin-top:16px;max-width:420px"><?php echo cpv2CsrfInput(); ?><input type="hidden" name="customer_id" value="<?php echo (int)$user['id']; ?>"><label><span>Relationship status</span><select name="status"><option value="Active" <?php echo $user['user_status']==='Active'?'selected':''; ?>>Active</option><option value="Suspended" <?php echo $user['user_status']==='Suspended'?'selected':''; ?>>Suspended</option></select></label><button class="op-btn secondary" type="submit" name="cpv2_customer_status" value="1">Update relationship status</button></form>
<?php endif; ?>
<?php if(strtolower((string)$user['user_status'])==='restricted'): ?>
<div class="op-alert error" style="margin-top:16px"><strong>Customer access is restricted.</strong><br><?php echo htmlspecialchars((string)$user['restriction_reason']); ?><br><small>Restricted by <?php echo htmlspecialchars((string)$user['restricted_by']); ?> · <?php echo htmlspecialchars((string)$user['restricted_at']); ?></small></div>
<form method="post" class="op-form" style="margin-top:12px;max-width:420px"><?php echo cpv2CsrfInput(); ?><input type="hidden" name="customer_id" value="<?php echo (int)$user['id']; ?>"><button class="op-btn primary" type="submit" name="cpv2_restore_customer" value="1" onclick="return confirm('Restore this customer’s online banking access?')">Restore customer access</button></form>
<?php else: ?>
<form method="post" class="op-form" style="margin-top:16px;max-width:520px"><?php echo cpv2CsrfInput(); ?><input type="hidden" name="customer_id" value="<?php echo (int)$user['id']; ?>"><label><span>Restriction / investigation reason</span><textarea name="restriction_reason" minlength="8" maxlength="1200" required placeholder="State why this customer’s online banking access is being restricted. This reason will be included in the customer email."></textarea></label><button class="op-btn danger" type="submit" name="cpv2_restrict_customer" value="1" onclick="return confirm('Restrict this customer’s online banking access?')">Restrict / archive customer access</button></form>
<?php endif; ?>
</section>
<div class="op-two">
<section class="op-panel"><div class="op-panel-head"><div><span class="op-kicker">ACCOUNTS</span><h2><?php echo count($accounts); ?> accounts</h2></div></div><div class="op-list"><?php foreach($accounts as $a):?><article><span class="material-symbols-rounded">account_balance</span><div><strong><?php echo htmlspecialchars($a['account_alias']?:$a['account_type']); ?></strong><small><?php echo htmlspecialchars($a['currency'].' · '.$a['account_number'].' · '.$a['account_status']); ?></small></div><a href="/control-panel/accounts/?account=<?php echo urlencode($a['account_number']); ?>">View</a></article><?php endforeach;?></div></section>
<aside class="op-panel"><div class="op-panel-head"><div><span class="op-kicker">IDENTITY</span><h2>KYC profile</h2></div></div><?php if($kyc):?><div class="op-detail"><div><dt>Status</dt><dd><?php echo htmlspecialchars($kyc['status']); ?></dd></div><div><dt>Occupation</dt><dd><?php echo htmlspecialchars($kyc['occupation']?:'—'); ?></dd></div><div><dt>Residence</dt><dd><?php echo htmlspecialchars($kyc['country_of_residence']); ?></dd></div><div><dt>Submitted</dt><dd><?php echo htmlspecialchars($kyc['time_uploaded']); ?></dd></div></div><a class="op-btn secondary" style="margin-top:14px" href="/control-panel/kyc/detail/?id=<?php echo (int)$kyc['id']; ?>">Open KYC</a><?php else:?><div class="op-alert error">No KYC submission.</div><?php endif;?></aside>
</div>
<section class="op-panel" style="margin-top:18px"><div class="op-panel-head"><div><span class="op-kicker">ACTIVITY</span><h2>Recent transactions</h2></div></div><div class="op-table-wrap"><table class="op-table"><thead><tr><th>Reference</th><th>Type</th><th>Status</th><th>Amount</th><th>Date</th></tr></thead><tbody><?php foreach($tx as $r):?><tr><td><?php echo htmlspecialchars($r['transaction_id']); ?></td><td><?php echo htmlspecialchars($r['type']); ?></td><td><?php echo htmlspecialchars($r['status']); ?></td><td><?php echo htmlspecialchars(velmoraFormatCurrency((float)$r['amount'],$r['currency'])); ?></td><td><?php echo htmlspecialchars(date('M d, Y H:i',(int)$r['time'])); ?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php cpv2End(); ?>